# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Question(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, text: str=None, type: str=None, options: List[str]=None):  # noqa: E501
        """Question - a model defined in Swagger

        :param id: The id of this Question.  # noqa: E501
        :type id: int
        :param text: The text of this Question.  # noqa: E501
        :type text: str
        :param type: The type of this Question.  # noqa: E501
        :type type: str
        :param options: The options of this Question.  # noqa: E501
        :type options: List[str]
        """
        self.swagger_types = {
            'id': int,
            'text': str,
            'type': str,
            'options': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'text': 'text',
            'type': 'type',
            'options': 'options'
        }
        self._id = id
        self._text = text
        self._type = type
        self._options = options

    @classmethod
    def from_dict(cls, dikt) -> 'Question':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Question of this Question.  # noqa: E501
        :rtype: Question
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Question.


        :return: The id of this Question.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Question.


        :param id: The id of this Question.
        :type id: int
        """

        self._id = id

    @property
    def text(self) -> str:
        """Gets the text of this Question.


        :return: The text of this Question.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this Question.


        :param text: The text of this Question.
        :type text: str
        """

        self._text = text

    @property
    def type(self) -> str:
        """Gets the type of this Question.


        :return: The type of this Question.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Question.


        :param type: The type of this Question.
        :type type: str
        """

        self._type = type

    @property
    def options(self) -> List[str]:
        """Gets the options of this Question.


        :return: The options of this Question.
        :rtype: List[str]
        """
        return self._options

    @options.setter
    def options(self, options: List[str]):
        """Sets the options of this Question.


        :param options: The options of this Question.
        :type options: List[str]
        """

        self._options = options
