# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Survey(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, title: str=None, description: str=None, status: str=None):  # noqa: E501
        """Survey - a model defined in Swagger

        :param id: The id of this Survey.  # noqa: E501
        :type id: int
        :param title: The title of this Survey.  # noqa: E501
        :type title: str
        :param description: The description of this Survey.  # noqa: E501
        :type description: str
        :param status: The status of this Survey.  # noqa: E501
        :type status: str
        """
        self.swagger_types = {
            'id': int,
            'title': str,
            'description': str,
            'status': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'description': 'description',
            'status': 'status'
        }
        self._id = id
        self._title = title
        self._description = description
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Survey':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Survey of this Survey.  # noqa: E501
        :rtype: Survey
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Survey.


        :return: The id of this Survey.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Survey.


        :param id: The id of this Survey.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Survey.


        :return: The title of this Survey.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Survey.


        :param title: The title of this Survey.
        :type title: str
        """

        self._title = title

    @property
    def description(self) -> str:
        """Gets the description of this Survey.


        :return: The description of this Survey.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Survey.


        :param description: The description of this Survey.
        :type description: str
        """

        self._description = description

    @property
    def status(self) -> str:
        """Gets the status of this Survey.


        :return: The status of this Survey.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Survey.


        :param status: The status of this Survey.
        :type status: str
        """

        self._status = status
